######################################################################
# Automatically generated by qmake (3.0) Mon Jul 2 00:00:07 2018
######################################################################

TEMPLATE = app
TARGET = audio-alignment
INCLUDEPATH += . external/kiss_fft/tools external/kiss_fft

# Input
HEADERS += audioCorrelation.h \
           audioCorrelationInfo.h \
           audioEnvelope.h \
           audioInfo.h \
           audioStreamInfo.h \
           fftCorrelation.h \
           fftTools.h \
           external/kiss_fft/kiss_fft.h \
           external/kiss_fft/tools/kiss_fftr.h
SOURCES += audioCorrelation.cpp \
           audioCorrelationInfo.cpp \
           audioEnvelope.cpp \
           audioInfo.cpp \
           audioStreamInfo.cpp \
           fftCorrelation.cpp \
           fftTools.cpp \
           main.c \
           external/kiss_fft/kiss_fft.c \
           external/kiss_fft/tools/kiss_fftr.c 
